---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-00
spec:
  selector:
    matchLabels:
      app: nginx-00
  template:
    metadata:
      labels:
        app: nginx-00
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-00
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-00
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-01
spec:
  selector:
    matchLabels:
      app: nginx-01
  template:
    metadata:
      labels:
        app: nginx-01
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-01
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-01
  type: LoadBalancer