---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-pool
  namespace: metallb-system 
spec:
  addresses:
  - 192.168.1.40-192.168.1.59
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lap-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - lab-pool
